# ---------------- Architecture -----------------
latent_dim: 64          # size of latent vector h_t
action_dim: 4           # grid-world: 4 moves; change for Procgen

# ---------------- Optimisation -----------------
learning_rate: 3e-4
batch_size: 32
epochs: 50              # number of dataset passes
device: cuda            # “cpu” if no GPU

# ---------------- Search -----------------------
max_iters: 10           # tree-expansion steps
temperature: 1.0        # softmax temperature

# ---------------- Loss weights -----------------
lambda_q:          1.0   # supervised Q
lambda_d:          0.1   # CQL penalty
lambda_t:          1.0   # transition consistency
lambda_r:          1.0   # reward consistency
lambda_reinforce:  0.0   # set >0 to turn on REINFORCE term
